### ISSUE TITLE
Update the self-deploy section Set up your secrets

### ISSUE THREAD

**Issue by Adito5393** [hankhank10/loglink-docs#1]
The [Set up your secrets](https://loglink.it/self-deploy/#set-up-your-secrets) should be update to reflect the new [env vars](https://github.com/hankhank10/loglink-server/commit/193a0c8996571fc6851ecea96fea5e7135b46422) support. Right?

**Comment by hankhank10** [comment]
Thank you. I had missed that this needed updating but it is now done.
